server:
  port: 8085

spring:
  application:
    name: api_gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: delivery_user_service
          uri: lb://DELIVERY_USER_SERVICE
          predicates:
            - Path=/api/users/**,/api/auth/**

        - id: restaurant_service
          uri: lb://RESTAURANT_SERVICE
          predicates:
            - Path=/api/restaurants/**

        - id: meal_service
          uri: lb://MEAL_SERVICE
          predicates:
            - Path=/api/meals/**

        - id: order_service
          uri: lb://ORDER_SERVICE
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
